### ISSUE TITLE
Typings file specified in package.json but not included in package

### ISSUE THREAD

**Issue by casieber** [drcmda/react-animated-tree#2]
Currently the package.json file specifies `"typings": "index.d.ts"` as well as referencing `"index.d.ts"` in the `files` property, but there is no `index.d.ts` in either the repo or in the final npm package currently.

If you're open to it, I'd be happy to create a PR for a simple d.ts file either here or to DefinitelyTyped.

**Comment by drcmda** [comment]
@casieber whoops, i tend to copy over projects, must've missed it. I'd be super glad to receive PR's!
